# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Common
javaVersion=25
minecraftVersion=26.2
minecraftDisplayVersion=26.2

# Fabric
fabricLoaderVersion=0.19.3
fabricVersion=0.153.0+26.2
fabricMinecraftVersionRange=~26
# ~1.x.1 <-> 1.x.1, 1.x.2, ...

# Forge
forgeVersion=65.0.2
forgeVersionRange=[65,)
forgeMinecraftVersionRange=[26,27)

# NeoForge
neoforgeVersion=26.2.0.7-beta
neoforgeVersionRange=[26,27)
neoforgeMinecraftVersionRange=[26,27)