# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Common
javaVersion=21
minecraftVersion=1.21.1
minecraftDisplayVersion=1.21.1

# Fabric
fabricLoaderVersion=0.16.9
fabricVersion=0.102.0+1.21.1
fabricMinecraftVersionRange=~1.21
# ~1.x.1 <-> 1.x.1, 1.x.2, ...

# Forge
forgeVersion=52.0.33
forgeVersionRange=[51,)
forgeMinecraftVersionRange=[1.21,1.22)

# NeoForge
neoforgeVersion=21.1.65
neoforgeVersionRange=[21,)
neoforgeMinecraftVersionRange=[1.21,1.22)
