modLoader = "javafml"
loaderVersion = "${forgeVersionRange}"
license = "Apache 2.0"
issueTrackerURL = "${modIssueTrackerUrl}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
updateJSONURL = "${modUpdateJsonUrl}"
displayURL = "${modDisplayUrl}"
#logoFile = ""
#credits = ""
authors = "${modAuthors}"
displayTest = "IGNORE_SERVER_VERSION"
description = '''${modDescription}'''

[[dependencies.${ modId }]]
modId = "forge"
mandatory = true
versionRange = "${forgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"
