# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Common
javaVersion=25
minecraftVersion=26.3
minecraftDisplayVersion=26.3

# Fabric
fabricLoaderVersion=0.19.3
fabricVersion=0.161.0+26.3
fabricMinecraftVersionRange=^26.3
# ~1.x.1 <-> 1.x.1, 1.x.2, ...

# Forge
forgeVersion=66.0.0
forgeVersionRange=[62,)
forgeMinecraftVersionRange=[26,27)

# NeoForge
neoforgeVersion=26.3.0.6-beta
neoforgeVersionRange=[26,27)
neoforgeMinecraftVersionRange=[26,27)