name: 'Build all'
run-name: Build all -${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'dev'

jobs:
  build-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcversion: [ "1.19.x", "1.20.x" ]
    steps:
      - uses: ./.github/workflows/build-${{ matrix.mcversion }}.yml
        with:
          version: ${{ inputs.version }}