name: 'Build all'
run-name: Build all-${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'dev'

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-1.19.x.yml
        with:
          version: ${{ inputs.version }}
      - uses: ./.github/workflows/build-1.20.x.yml
        with:
          version: ${{ inputs.version }}