name: "Build 1.21.5"
run-name: Build 1.21.5-${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0-dev"
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-1-21-5:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mc2discord-1.21.5
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-1.21.5-${{ runner.os }}-${{ hashFiles('**/gradle.properties', '**/build.gradle.kts', '**/settings.gradle', '**/gradle-wrapper.jar') }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          INPUT_VERSION: ${{ inputs.version }}
      - uses: actions/upload-artifact@v4
        with:
          name: mc2discord-forge-1.21.5-${{ inputs.version }}
          path: |
            ${{ github.workspace }}/mc2discord-1.21.5/forge/build/libs/
            !${{ github.workspace }}/mc2discord-1.21.5/forge/build/libs/*-slim.jar
      - uses: actions/upload-artifact@v4
        with:
          name: mc2discord-fabric-1.21.5-${{ inputs.version }}
          path: |
            ${{ github.workspace }}/mc2discord-1.21.5/fabric/build/libs/
            !${{ github.workspace }}/mc2discord-1.21.5/fabric/build/libs/*-all.jar
