name: 'Build 1.20.x'
run-name: Build 1.20.x-${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'dev'
        
jobs:
  build-1-20-x:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: mc2discord-forge-1.20.x
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: build-1.20.x-${{ inputs.version }}
          path: |
              ${{ github.workspace }}/mc2discord-forge-1.20.x/build/libs/
              !${{ github.workspace }}/mc2discord-forge-1.20.x/build/libs/*-slim.jar