name: "Build all"
run-name: Build all-${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0-dev"
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-1-18-x:
    uses: ./.github/workflows/build-1.18.x.yml
    with:
      version: ${{ inputs.version }}

  build-1-19-x:
    uses: ./.github/workflows/build-1.19.x.yml
    with:
      version: ${{ inputs.version }}

  build-1-20-1:
    uses: ./.github/workflows/build-1.20.1.yml
    with:
      version: ${{ inputs.version }}

  build-1-20-2:
    uses: ./.github/workflows/build-1.20.2.yml
    with:
      version: ${{ inputs.version }}

  build-1-20-x:
    uses: ./.github/workflows/build-1.20.x.yml
    with:
      version: ${{ inputs.version }}

  build-1-21-x:
    uses: ./.github/workflows/build-1.21.x.yml
    with:
      version: ${{ inputs.version }}

  build-1-21-5:
    uses: ./.github/workflows/build-1.21.5.yml
    with:
      version: ${{ inputs.version }}
