name: 'Build all'
run-name: Build all-${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'dev'

jobs:
  build-all:
    strategy:
      matrix:
        mc-version:
          - '1.20.x'
          - '1.19.x'
    uses: ./.github/workflows/build-${{ matrix.mc-version }}.yml
    with:
      version: ${{ inputs.version }}