name: 'Publish fabric 1.20.x'
run-name: Publish fabric-1.20.x-${{ inputs.version }}

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      MODRINTH_TOKEN:
        required: true
      CURSEFORGE_TOKEN:
        required: true
      WEBHOOK_URL:
        required: true

jobs:
  publish-fabric-1-20-x:
    runs-on: ubuntu-latest
    needs: build-fabric-1-20-x
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Cfbcv7uF
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 325235
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-unfeature-mode: intersection

          files: mc2discord-fabric-1.20.x-${{ inputs.version }}/mc2discord-fabric-1.20.x-${{ inputs.version }}.jar
          name: '[Fabric 1.20.x] ${{ inputs.version }}'
          changelog-file: CHANGELOG.md
          loaders: |
            fabric
          game-versions: |
            1.20
            1.20.1
      - uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: 'New Mc2Discord version released: [Fabric 1.20.x] ${{ inputs.version }}'