name: 'Publish forge 1.20.2'
run-name: Publish forge-1.20.2-${{ inputs.version }}

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      MODRINTH_TOKEN:
        required: true
      CURSEFORGE_TOKEN:
        required: true
      WEBHOOK_URL:
        required: true

jobs:
  publish-forge-1-20-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4.1.7
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Cfbcv7uF
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 325235
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-unfeature-mode: intersection

          files: mc2discord-forge-1.20.2-${{ inputs.version }}/mc2discord-forge-1.20.2-${{ inputs.version }}.jar
          name: '[Forge 1.20.2] ${{ inputs.version }}'
          changelog-file: CHANGELOG.md
          loaders: |
            forge
          game-versions: |
            1.20.2
      - uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: 'New Mc2Discord version released: [Forge 1.20.2] ${{ inputs.version }}'
